/**
 * Task Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskDto { 
    /**
     * Unikalny identyfikator zadania
     */
    id: number;
    /**
     * Tytuł zadania
     */
    title: string;
    /**
     * Szczegółowy opis zadania
     */
    description: string;
    /**
     * Czy zadanie zostało ukończone?
     */
    completed: boolean;
    /**
     * Deadline dla zadania
     */
    date: string;
}

